### ISSUE TITLE
Mountain's Blessing and possibly other passives support

### ISSUE THREAD

**Issue by wjtk4444** [cloudor126/lua-eso-addon-adr#1]
Dragonknight skill line called Earthen Heart has a passive skill named Mountain's Blessing which gives Minor Brutality for 20 seconds. I would expect other classes / skill lines to have similar passives (second effect with different duration). Would it be possible for ADR to support those? If not, is there any simple way I could hardcode a 20s long second second effect for Igneous Shield skill? That's really the only thing I care about. I skimmed trough the code, but it didn't get me anywhere, not at the first glance at least.

**Comment by cloudor126** [comment]
Sorry for not replying for such a long time. I recommend using [Srendarr ](https://www.esoui.com/downloads/info655-Srendarr-AuraBuffDebuffTracker.html) to track a general buff out of several actions.
