### ISSUE TITLE
Subterrain Assault changes

### ISSUE THREAD

**Issue by edrzns** [cloudor126/lua-eso-addon-adr#2]
Addon no longer trackcs Subterrain assault skill correctly after Martkarth update (u28), because skill was changed as described in patch notes:
  - Subterranean Assault (morph):
    - This morph no longer applies Fracture, as Deep Fissure now affects all Armor. This ability now recasts itself after completing, once per cast.

So in general, timer should be 6 seconds after cast if I understood correctly

**Comment by cloudor126** [comment]
Sorry for not replying for such a long time.  This bug should have been fixed already.
