### ISSUE TITLE
Large lag spikes with the Azureblight Reaper set

### ISSUE THREAD

**Issue by hiranya911** [cloudor126/lua-eso-addon-adr#3]
With the Azureblight Reaper set equipped, this addon causes huge lag spikes in large add pulls. As more and more enemies are affected by the Blight Seed effect of the set, game performance degrades severely. Turning off this addon returns things to normal.

See here for a discussion on this issue: https://forums.elderscrollsonline.com/en/discussion/comment/6843400/#Comment_6843400

Is there anything that can be done in the implementation of the addon to avoid this sort of issues?

**Comment by BoltActionBalrog** [comment]
I created a pull request which I believe would address this issue https://github.com/cloudor126/lua-eso-addon-adr/pulls
